"""PlatformIO pre-build step: embed firmware/web/*.html into a C++ header.

The UI is kept as a real .html file so it stays editable and lintable, and is
gzipped at build time. Gzip matters here: it cuts the page to roughly a third,
and the AP has no internet, so every byte the browser needs must come off the
device itself.
"""

import gzip
import os

Import("env")  # noqa: F821


def build_header(source, target, env):
    project_dir = env.subst("$PROJECT_DIR")
    src = os.path.join(project_dir, "web", "index.html")
    dst = os.path.join(project_dir, "src", "web", "WebAssets.h")

    if not os.path.isfile(src):
        print("[ghosthid] no web/index.html; skipping asset embed")
        return

    raw = open(src, "rb").read()
    packed = gzip.compress(raw, 9)

    lines = []
    for i in range(0, len(packed), 16):
        chunk = packed[i:i + 16]
        lines.append("    " + " ".join("0x%02x," % b for b in chunk))

    os.makedirs(os.path.dirname(dst), exist_ok=True)
    with open(dst, "w") as f:
        f.write("// Generated by scripts/embed_web.py -- do not edit.\n")
        f.write("// Source: web/index.html (%d bytes raw, %d gzipped)\n\n"
                % (len(raw), len(packed)))
        f.write("#pragma once\n\n#include <stdint.h>\n#include <stddef.h>\n\n")
        f.write("namespace ghosthid {\n\n")
        f.write("inline const uint8_t kIndexHtmlGz[] = {\n")
        f.write("\n".join(lines))
        f.write("\n};\n\n")
        f.write("inline constexpr size_t kIndexHtmlGzLen = sizeof(kIndexHtmlGz);\n\n")
        f.write("}  // namespace ghosthid\n")

    print("[ghosthid] embedded web/index.html: %d -> %d bytes gzipped"
          % (len(raw), len(packed)))


# Run before anything is compiled, so the generated header is always current.
build_header(None, None, env)  # noqa: F821
